# Makefile for awk
#
# Copyright (c) 2022 Wind River Systems, Inc.
#
#

PKG_URL=https://github.com/onetrueawk/awk/archive/refs/heads/master.zip

#PKG_SHA512=083f5e675d73f3233c7930ebe20425a533feedeaaa9d8cc86831312a6581cefbe6ed0d08d2fa89be81082f2a5abdabca8b3c080bf97218a1bd59dc118a30b9f3


PKG_BUILD_DIR= awk-master

PKG_FILE_TYPE = unpack


PKG_BUILD_TARGETS := awk

include $(WIND_KRNL_MK)/rules.unix.ports.mk
